[공통] 비기너가 볼 수 있는 페이지 제한
BCSDLab/BCSD_INTERNAL_WEB pull request #110
Opened 2024-03-14 08:41 UTC by chaeseungyun

## [Copy here issue number] request

비기너 직위로 로그인 시 트랙정보, 직책정보, 마이페이지에만 접근할 수 있도록 수정했습니다.
사이드바를 통해 다른 곳으로 이동 시 에러 메시지를 띄우며 트랙정보 화면으로 리다이렉트됩니다.

## Please check if the PR fulfills these requirements

- [ ] The commit message follows our guidelines
- [ ] Did you merge recent `main` branch?

### Screenshot
![image](https://github.com/BCSDLab/BCSD_INTERNAL_WEB/assets/101871802/0cbca2b0-1030-4da2-a8b9-2d38e6eb6046)

### Precautions (main files for this PR ...)

- Close #ISSUE_NUMBER

2024-03-14 08:46 UTC, MinGu-Jeong commented on src/App.tsx
> +  }, []);
약간 편견일 수 있긴한데, useEffect에 의존성 배열을 비워둬도 되나요?

2024-03-14 08:47 UTC, MinGu-Jeong commented on src/layout/DefaultLayout/index.tsx
> +const beginnerPage = ['/track', '/role', '/mypage'];
👍👍👍

2024-03-14 13:26 UTC, chaeseungyun commented on src/App.tsx
> +  }, []);
페이지 마운트될 때 한 번만 로그인 정보를 저장하면 될 것이다라고 판단했습니다
더 좋은 방법이 있을까요?

2024-03-14 14:38 UTC, MinGu-Jeong commented on src/App.tsx
> +  }, []);
```suggestion
  useEffect(
    () => {
      setMe();
    },
    [setMe],
  );
```
물론 의도상 빈배열을 쓰는게 맞긴하지만 setMe를 의존성 배열에 넣어 관리해주는게 lint룰상 더 적절할 것 같기도 합니다

2024-03-14 14:47 UTC, dooohun requested changes
수고하셨습니다!
처음 로그인을 하면 회원 정보를 갔다가, 트랙 정보로 이동을 하는데, 그렇게 되면 접근 권한 에러 문구를 반드시 봐야 한다는 문제점이 있는 거 같습니다.

2024-03-14 14:47 UTC, dooohun commented on src/layout/DefaultLayout/index.tsx
> +  }
좋은 거 같습니다!
개인적인 생각이지만 일종에 동기부여(?)에도 도움이 될 수도 있을 거 같네요 ㅋㅋㅋㅋ
(내가 비기너 반드시 벗어나서 저기 들어간다 <- 요런 느낌?)

2024-03-14 14:47 UTC, dooohun commented on src/store/loginStore.ts
로그인 상태를 전역적으로 관리하는 방식 좋습니다! 👍
다른 곳에서 많이 쓸 거 같네요!

2024-03-14 14:47 UTC, dooohun commented on src/App.tsx
> +      <Route element={<AuthRoute needAuth redirectRoute="/" />}>
현재 회원가입을 완료하면 `SignUp` 컴포넌트에 `useMutation`에 있는 `onSuccess`의 naviagte('/login')으로 설정되어 있는데, `navigate('/')`로 수정해야 할 거 같아요!

2024-03-14 14:54 UTC, MinGu-Jeong commented on src/App.tsx
> +      <Route element={<AuthRoute needAuth redirectRoute="/" />}>
아 이거 QA때 놓친건 줄 알고 이슈 올려놨는데 이번에 생긴 오류였네요 ㅋㅋㅋ
- https://github.com/BCSDLab/BCSD_INTERNAL_WEB/issues/111

2024-03-15 03:23 UTC, junghaesung79 reviewed
고생하셨습니다!
궁금한 것 적어둘게요!

2024-03-15 03:23 UTC, junghaesung79 commented on src/layout/DefaultLayout/index.tsx
> +    navigate('/track');
만약에의 이야기이지만 주소로 검색해서 들어가는 것도 정상적으로 막아지는 지 궁금합니다!

2024-03-15 03:23 UTC, junghaesung79 commented on src/layout/DefaultLayout/index.tsx
> +    navigate('/track');
그리고 혹시 보고 있던 페이지에 머무르는 것이 아니라 무조건 /track으로 넘어가도록 하는 이유가 있나요?

2024-03-18 12:05 UTC, chaeseungyun commented on src/layout/DefaultLayout/index.tsx
> +    navigate('/track');
@MinGu-Jeong 님과 처음 의논한 결과였습니다!

2024-03-18 12:45 UTC, dooohun approved these changes
수고하셨습니다~

2024-03-18 12:45 UTC, dooohun commented on src/query/members.ts
> +      else navigate('/member');
오 훨씬 깔끔한 것 같아요!! 너무 좋습니다!

2024-03-18 12:45 UTC, dooohun commented on src/query/members.ts
> +      setMe();
좋습니다 👍

2024-03-18 12:48 UTC, merged