[팀 관리페이지] 팀 관리페이지 구현
BCSDLab/BCSD_INTERNAL_WEB pull request #178
Opened 2024-05-23 15:44 UTC by Choi-JJunho

## Please check if the PR fulfills these requirements

- [ ] The commit message follows our guidelines
- [ ] Did you merge recent `main` branch?

### Screenshot

https://github.com/BCSDLab/BCSD_INTERNAL_WEB/assets/49794401/92afb603-8ba3-42fa-9c89-50acc53a6f3c

2024-05-23 15:53 UTC, MinGu-Jeong commented on src/component/alertModal/index.tsx
> +  onConfirm: () => any;
`void`타입 사용은 어떠신가요?
```suggestion
  onConfirm: () => void;
```

2024-05-23 16:00 UTC, MinGu-Jeong commented on src/component/modal/teamAddMemberModal/index.tsx
> +}: SearchMemberModalProps) => {
마이너?) 리액트에서 컴포넌트를 선언할 때는 다음과 같은 컨벤션을 가지는 편이에요
변수랑 컴포넌트를 구분하기 용이하게 하기 위해서입니다.
그런데 기능상 동일하긴 해서 큰 문제는 안될 것 같아요
```suggestion
export default function SearchModal({
  open, onClose, teamId, isLeader,
}: SearchMemberModalProps) {
```

2024-05-23 16:03 UTC, MinGu-Jeong commented on src/component/modal/teamAddMemberModal/index.tsx
> +}: SearchMemberModalProps) => {
+) memo를 사용했다면 얘기가 달라지긴 하네요
memo를 사용한다면 이렇게 사용할 수 있다고 합니당
```suggestion
function SearchModal({
  open, onClose, teamId, isLeader,
}: SearchMemberModalProps) {

~~~

export default memo(SearchModal);
```

2024-05-23 16:07 UTC, MinGu-Jeong commented on src/component/modal/teamAddMemberModal/index.tsx
> +  const handleSearchChange = useCallback((e: any) => {
TextField에서 변경되는 이벤트 타입은 `React.ChangeEvent<HTMLInputElement>`이므로 이걸 적용해주면 좋을 것 같아요
```suggestion
  const handleSearchChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
```

2024-05-23 16:24 UTC, Choi-JJunho commented on src/component/alertModal/index.tsx
> +  onConfirm: () => any;
그러네요 반환하는 값이 없으니 굳이 any일 필요가 없겠네요

2024-05-23 17:08 UTC, chaeseungyun requested changes
굿~ 이제 suspenseQuery를 사용하는 곳에서 가장 가까운 컨테이너를 suspense로 감싸봅시다

2024-05-23 17:08 UTC, chaeseungyun commented on src/component/modal/teamUpdateModal/index.tsx
> +              {teamMembers?.filter((member) => member.isLeader === true)
suspenceQuery인데 옵셔널 체이닝이 필요한가요

2024-05-27 03:07 UTC, Choi-JJunho commented on src/component/modal/teamAddMemberModal/index.tsx
> +    pageIndex: 0, pageSize: 1000, name: searchQuery,
아직 필요성을 못느껴서 임의로 위와같이 구성해뒀습니다.
다른 코드를 참고하여 작성하다보니 위처럼 구성된 면도 있습니다.

2024-05-27 03:08 UTC, Choi-JJunho commented on src/component/modal/teamUpdateModal/index.tsx
> +              {teamMembers?.filter((member) => member.isLeader === true)
오 확실히 suspenceQuery에서는 Optional chaining이 필요 없겠네요
수정하겠습니다.

2024-05-27 13:31 UTC, chaeseungyun reviewed
이거 suspense로 감싸주지 않아도 렌더링에 문제 없나요?

2024-05-27 13:50 UTC, Choi-JJunho commented
네~!

2024-05-28 08:30 UTC, chaeseungyun approved these changes

2024-05-28 08:31 UTC, merged